"use client";
import Image from "next/image";
import React, { useState } from "react";
import TableBrands from "@/components/organisms/TableBrands";
import ModalCreateBrand from "@/components/organisms/Modals/ModalCreateBrand";

export const metadata = {
	title: "Data Brands",
	description: "Generated by create next app",
};

function BrandsData() {
	return (
		<div className="my-10 ml-[90px] mr-5 lg:ml-[20%] lg:mr-[18%]">
			<div>
				<h1 className="text-2xl lg:text-4xl font-semibold">Brands Data</h1>
			</div>

			{/* DATA BRANDS */}
			<div className="border-2 border-dashed border-black p-7 lg:p-10 rounded-lg mt-10">
				<ModalCreateBrand />
				<div className="relative overflow-x-auto shadow-md sm:rounded-lg">
					<TableBrands />
				</div>
			</div>
		</div>
	);
}

export default BrandsData;
