"use client";
import TextFormField from "@/components/textFormField";
import UploadPhoto from "./uploadPhoto";
import { useState } from "react";

export const metadata = {
  title: "Edit My Profile",
  description: "Generated by create next app",
};

function Profile() {
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [occupation, setOccupation] = useState("");
  const [image, setImage] = useState("");
  const [imagePreview, setImagePreview] = useState("");

  const onSubmit = () => {
    console.log("name :", name);
    console.log("phone :", phone);
    console.log("occupation :", occupation);
    console.log("image: ", image);
  };

  const onImageUpload = (e) => {
    const file = e.target.files[0];
    setImage(file);
    setImagePreview(URL.createObjectURL(file));
  };

  return (
    <div className="lg:mb-0 lg:mt-10 lg:ml-[25%] w-full lg:w-auto select-none">
      <h1 className="text-4xl font-bold text-indigo-950">Edit Profile</h1>
      <p className="mt-2 text-gray-400">
        Input your valid information <br /> and let's rent our cars
      </p>
      <div className="my-10">
        <div className="flex flex-col rounded-2xl bg-darkGrey p-8">
          <h3>My Avatar (Max. 1MB)</h3>
          {/* Img */}
          <UploadPhoto onChange={(e) => onImageUpload(e)} img={imagePreview} />

          <form className="space-y-2 mt-8">
            <TextFormField
              label={"Username"}
              type={"text"}
              disabled={true}
              placeholder={"jhondoe"}
            />
            <TextFormField
              label={"Email"}
              type={"email"}
              disabled={true}
              placeholder={"jhondoe@gmail.com"}
            />
            <TextFormField
              label={"Name"}
              type={"text"}
              onChange={(e) => setName(e.target.value)}
            />

            <TextFormField
              label={"Phone"}
              type={"number"}
              onChange={(e) => setPhone(e.target.value)}
            />
            <TextFormField
              label={"My Occupation"}
              type={"text"}
              onChange={(e) => setOccupation(e.target.value)}
            />
          </form>
          <button
            onClick={onSubmit}
            className="bg-blue-500 mt-8 w-auto py-2 rounded-full shadow-lg shadow-blue-400"
          >
            <h1 className="text-white font-semibold text-lg ">SUBMIT</h1>
          </button>
        </div>
      </div>
    </div>
  );
}

export default Profile;
