import Header from "@/components/Header";
import React from "react";

export const metadata = {
  title: "Stories",
  description: "Generated by create next app",
};

function Stories() {
  return (
    <>
      <div>Stories Page</div>
    </>
  );
}

export default Stories;
