import SidebarAdmin from "@/components/organisms/SidebarAdmin";

export const metadata = {
  title: { default: "Admin", template: "%s" },
  description: "Generated by create next app",
};

function AdminLayout({ children }) {
  return (
    <div className="bg-[#393E46] h-screen flex">
      <SidebarAdmin />
      {children}
    </div>
  );
}

export default AdminLayout;
