import React from "react";

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

function Admin() {
  return (
    <div>
      <h1 className="text-white text-xl">Hello</h1>
    </div>
  );
}

export default Admin;
