import MapsContent from "@/components/mapsContent";
import React from "react";

export const metadata = {
  title: "Maps",
  description: "Generated by create next app",
};

function Maps() {
  return (
    <div className="mx-6 pt-4 md:mx-10 lg:mx-52 lg:pt-10 ">
      <MapsContent />
    </div>
  );
}

export default Maps;
