"use client";
import Image from "next/image";
import React, { useState } from "react";
import TableCars from "@/components/organisms/TableCars";

export const metadata = {
	title: "Data Cars",
	description: "Generated by create next app",
};

function CarsData() {
	return (
		<div className="my-10 ml-[90px] mr-5 lg:ml-[20%] lg:mr-[18%]">
			<div>
				<h1 className="text-2xl lg:text-4xl font-semibold">Cars Data</h1>
			</div>

			{/* DATA CARS */}
			<div className="border-2 border-dashed border-black p-7 lg:p-10 rounded-lg mt-10">
				<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
					<TableCars />
				</div>
			</div>
		</div>
	);
}

export default CarsData;
