import TextFormField from "@/components/textFormField";
import React from "react";

export const metadata = {
  title: "Data Cars",
  description: "Generated by create next app",
};

function DataCars() {
  return (
    <div className="mt-10 ml-10">
      <div>
        <h1 className="text-white text-4xl font-semibold">Input Cars Data</h1>
      </div>

      <div className="border-2 border-dashed p-10 rounded-lg mt-10">
        <form action="" className="flex gap-4">
          <div>
            <h4 className="text-white">Car Name</h4>
            <input
              type="text"
              className="mt-2 focus:outline-none px-3 py-2 rounded-xl capitalize focus:ring-2 focus:ring-blue-500 caret-blue-500"
            />
          </div>
          <div>
            <h4 className="text-white">Brand Name</h4>
            <input
              type="text"
              className="mt-2 focus:outline-none px-3 py-2 rounded-xl capitalize focus:ring-2 focus:ring-blue-500 caret-blue-500"
            />
          </div>
          <div>
            <h4 className="text-white">Price</h4>
            <input
              type="number"
              className="mt-2 focus:outline-none px-3 py-2 rounded-xl capitalize focus:ring-2 focus:ring-blue-500 caret-blue-500"
            />
          </div>
        </form>
      </div>

      {/* SPEC DATA INPUT */}
      <div className="relative mt-10 p-10 border-2 border-dashed rounded-lg ">
        <h4 className="text-white text-xl">Specification Data</h4>
        <div className="absolute top-[80px] right-10 w-10 h-10 rounded-lg items-center justify-center flex bg-green-500 text-green-900 font-semibold text-center text-2xl cursor-pointer">
          +
        </div>
        <div className="mt-20 space-y-6">
          <input
            type="number"
            className="w-full  focus:outline-none px-3 py-2 rounded-xl capitalize focus:ring-2 focus:ring-blue-500 caret-blue-500"
          />
          <input
            type="number"
            className="w-full  focus:outline-none px-3 py-2 rounded-xl capitalize focus:ring-2 focus:ring-blue-500 caret-blue-500"
          />
          <input
            type="number"
            className="w-full  focus:outline-none px-3 py-2 rounded-xl capitalize focus:ring-2 focus:ring-blue-500 caret-blue-500"
          />
        </div>
      </div>
    </div>
  );
}

export default DataCars;
