import Navbar from "@/components/organisms/Navbar";

export const metadata = {
  title: { default: "Luxury Rent Car", template: "%s" },
  description: "Generated by create next app",
};

function UserLayout({ children }) {
  return (
    <div>
      <Navbar />
      {children}
    </div>
  );
}

export default UserLayout;
